#start_date: '2023-10-04'
#end_date: '2023-10-05'
base_currency: 'USD'
minio:
  endpoint: 'minio:9000'
  access_key: 'admin'
  secret_key: 'admin123'
  bucket_name: 'exchange-data'
postgres:
  dbname: 'mydatabase'
  user: 'postgres'
  password: 'postgres'
  host: 'postgres'
  port: 5432
